### ISSUE TITLE
Add GiftWrap Plugin to Travis-ci.org

### ISSUE THREAD

**Issue by justinyost** [loadsys/CakePHP-GiftWrap#10]
There is a .travis.yml file in the plugin but now we need to have GiftWrap added to https://travis-ci.org/

Same steps as adding a private Github repo just different domain.

**Comment by beporter** [comment]
Travis-ci.org webhook has been enabled. Will leave this open until testing is complete.

**Comment by justinyost** [comment]
Checking on this, doesn't look like I can do anything. Wondering if it shows up for you and if it will run the testing?
![screen shot 2014-02-28 at 3 16 35 pm](https://f.cloud.github.com/assets/85320/2299528/699f391e-a0ce-11e3-9a42-48a82b99f038.png)

**Comment by justinyost** [comment]
NVM

**Comment by justinyost** [comment]
I can see the repo and manage Travis builds even though I am not an admin (presumably because I can push/pull to the repo).
![screen shot 2014-02-28 at 3 18 22 pm](https://f.cloud.github.com/assets/85320/2299545/ad23daaa-a0ce-11e3-9ead-10133d497645.png)
