### ISSUE TITLE
GitHub Repo Admin Needs to Add Packagist Service Hook

### ISSUE THREAD

**Issue by justinyost** [loadsys/CakePHP-GiftWrap#8]
Packagist package here: https://packagist.org/packages/loadsys/cakephp_giftwrap

**Comment by beporter** [comment]
packagist webhook has been enabled. Leaving this open until testing is complete.

**Comment by justinyost** [comment]
Doesn't say it on the site yet, uggh.
![screen shot 2014-02-28 at 4 55 30 pm](https://f.cloud.github.com/assets/85320/2300010/436344da-a0dc-11e3-9b6a-d858c08b0815.png)

**Comment by justinyost** [comment]
Closing as package marked as abandoned.
